language: objective-c
osx_image: xcode11.3
xcode_workspace: DemoCI.xcworkspace
xcode_scheme: DemoCI
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 8
before_install:
  - bundle install
  - bundle exec pod install --repo-update
