language: objective-c
osx_image: xcode10.1
xcode_workspace: DemoTravisCI.xcworkspace
xcode_scheme: DemoTravisCI
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
  - bundle install
  - bundle exec pod install --repo-update
